app = "naive-proxy"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 443
  protocol = "tls"
  [services.ports]
    handlers = ["tls"]
    port = "443"
